jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: UsePythonVersion@0
        displayName: Setup Python
        inputs:
          versionSpec: '3.7'

      - bash: 'make install'
        displayName: Install Dependencies
        workingDirectory: '$(System.DefaultWorkingDirectory)'

      - bash: 'python -m pipenv run make per-commit'
        displayName: Build
        workingDirectory: '$(System.DefaultWorkingDirectory)'
