jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: UsePythonVersion@0
        displayName: Setup Python
        inputs:
          versionSpec: '3.7'

      - bash: 'make install'
        displayName: Install Dependencies
        workingDirectory: '$(System.DefaultWorkingDirectory)'

      - bash: 'export PYTHONPATH=$(pwd) && python -m pipenv run make per-commit'
        displayName: Build
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      
      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFiles: 'test_results/test_results.xml'
        condition: succeededOrFailed()
        workingDirectory: '$(System.DefaultWorkingDirectory)'
