trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - releases/*


jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: UsePythonVersion@0
        displayName: Setup Python
        inputs:
          versionSpec: '3.7'

      - bash: 'make install'
        displayName: Install Dependencies
        workingDirectory: '$(System.DefaultWorkingDirectory)'

      - bash: 'export PYTHONPATH=$(pwd) && python -m pipenv run make per-commit'
        displayName: Build
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      
      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFiles: 'test_results/test_results.xml'
        condition: succeededOrFailed()
      
      - bash: 'python -m pipenv run make publish-coverage'
        displayName: Publish Coverage Report to Coveralls
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        env:
          COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
  
  - job: Publish
    dependsOn:
      - Build
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/releases/'))
    pool:
      vmImage: 'Ubuntu 16.04'
    
    steps:
      - task: UsePythonVersion@0
        displayName: Setup Python
        inputs:
          versionSpec: '3.7'
      
      - bash: 'make install'
        displayName: Install Dependencies
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      
      - bash: 'python -m pipenv run make publish-pypi'
        displayName: Publish Package to PyPi
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        env:
          PYPI_USERNAME: $(PYPI_USERNAME)
          PYPI_PASSWORD: $(PYPI_PASSWORD)
